"""PuttTrack smart-ball telemetry protocol."""

from .telemetry import (
    MOTION_CHARACTERISTIC_UUID,
    PICKUP_SHADOW_REASON_BY_BIT,
    PICKUP_SHADOW_RULE_BY_BIT,
    PROTOCOL_VERSION,
    SERVICE_UUID,
    STATUS_CHARACTERISTIC_UUID,
    FrozenHistoryMetadata,
    MotionRecord,
    PickupShadowArmResult,
    PickupShadowResult,
    StatusRecord,
    TelemetryProtocolError,
    frozen_history_from_smp,
    frozen_history_metadata_from_smp,
    motion_from_smp,
    motion_window_from_smp,
    parse_motion,
    parse_status,
    pickup_shadow_arm_from_smp,
    pickup_shadow_result_from_smp,
    status_from_smp,
)
from .session import (
    TagCaptureReport,
    TagCaptureSession,
    TagIdentityError,
    normalize_device_id,
)

__all__ = [
    "MOTION_CHARACTERISTIC_UUID",
    "PICKUP_SHADOW_REASON_BY_BIT",
    "PICKUP_SHADOW_RULE_BY_BIT",
    "PROTOCOL_VERSION",
    "SERVICE_UUID",
    "STATUS_CHARACTERISTIC_UUID",
    "FrozenHistoryMetadata",
    "MotionRecord",
    "PickupShadowArmResult",
    "PickupShadowResult",
    "StatusRecord",
    "TagCaptureReport",
    "TagCaptureSession",
    "TagIdentityError",
    "TelemetryProtocolError",
    "frozen_history_from_smp",
    "frozen_history_metadata_from_smp",
    "motion_from_smp",
    "motion_window_from_smp",
    "parse_motion",
    "parse_status",
    "pickup_shadow_arm_from_smp",
    "pickup_shadow_result_from_smp",
    "status_from_smp",
    "normalize_device_id",
]
